spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/issuer"
    username: "in2admin"
    password: "in2pass"
    generate-unique-name: true
  flyway:
    url: "jdbc:postgresql://localhost:5432/issuer"
    locations: classpath:db/migration

app:
  configs:
    iam-external-domain: http://localhost:8088
    iam-internal-domain: http://localhost:8088
    issuer-external-domain: http://localhost:8071
    authentic-sources-domain: http://localhost:8072
    key-vault-domain: http://localhost:8081
    remote-signature-domain: http://localhost:8050
    issuer-did: "did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa"
    jwt-decoder-path: "/realms/EAAProvider/protocol/openid-connect/certs"
    jwt-decoder-local-path: "/realms/EAAProvider"
    jwt-validator: "http://localhost:8088/realms/EAAProvider"
    pre-auth-code-uri-template: "/realms/EAAProvider/verifiable-credential/{{did}}/credential-offer"
    token-uri-template: "/realms/EAAProvider/verifiable-credential/{{did}}/token"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true